# Generated by Django 4.2.4 on 2023-09-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(default='', max_length=255)),
                ('answer', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('f_name', models.CharField(default='', max_length=40)),
                ('email_id', models.EmailField(max_length=60, primary_key=True, serialize=False)),
                ('phnone', models.IntegerField(default=0, max_length=10)),
                ('address', models.TextField(default='', max_length=150)),
                ('gender', models.CharField(default='', max_length=7)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
