# Generated by Django 3.2.5 on 2023-09-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VA_ML', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='phnone',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
