# Generated by Django 3.2.5 on 2023-09-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VA_ML', '0002_alter_farmer_phnone'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='last_login',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='last login'),
        ),
    ]
