# Generated by Django 3.2.5 on 2023-09-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VA_ML', '0003_farmer_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='last_login',
        ),
    ]
