# Generated by Django 4.2.4 on 2023-09-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VA_ML', '0005_farmer_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='last_login',
        ),
    ]
