# Generated by Django 4.2.4 on 2023-10-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VA_ML', '0006_remove_farmer_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.FloatField(default='', max_length=10)),
                ('p', models.FloatField(default='', max_length=10)),
                ('k', models.FloatField(default='', max_length=10)),
                ('ph', models.FloatField(default='', max_length=10)),
                ('rainfall', models.FloatField(default='', max_length=10)),
                ('humidity', models.FloatField(default='', max_length=10)),
                ('temprature', models.FloatField(default='', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='farmer',
        ),
    ]
