# Generated by Django 4.2.4 on 2023-10-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VA_ML', '0008_new_data_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=70)),
                ('phn', models.ImageField(default=0, max_length=10, upload_to='')),
                ('desc', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
