# Generated by Django 4.2.4 on 2023-10-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VA_ML', '0009_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='contact_us',
            old_name='phn',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contact_us',
            name='id',
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(default='', max_length=70, primary_key=True, serialize=False),
        ),
    ]
