# Generated by Django 4.2.4 on 2023-10-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VA_ML', '0010_rename_desc_contact_us_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='contactUs',
        ),
    ]
